### PR TITLE
typo and add equivalence to Ellipsis represents

### PR DESCRIPTION
**Pull request by neilteng**
add equivalence to Ellipsis represents to better understand the bebavior of Ellipsis  ...

### CODE REVIEW

**Comment by neilteng** [comment]
add equivalence to Ellipsis represents to better understand the bebavior of Ellipsis ...

**Review by nbwuzhe — COMMENTED** [review]
@lyhue1991 I don't understand. There are three modifications. The first one of adding the word "but" is clearly changing the original meaning and is incorrect. The second one is unnecessary and the last one is a simple copy of the same cell.

**Comment by lyhue1991** [comment]
@nbwuzhe @neilteng  I don't understand too. 😂  😂

**Comment by neilteng** [comment]
@lyhue1991 @nbwuzhe  不好意思哈，看最后一个commit就好了，因为我直接在网页版上改，所以可能不小心commit多了几次。cherrypick最后一次的就可以了我觉得？

**Comment by nbwuzhe** [comment]
> @lyhue1991 @nbwuzhe 不好意思哈，看最后一个commit就好了，因为我直接在网页版上改，所以可能不小心commit多了几次。cherrypick最后一次的就可以了我觉得？

There is only one commit in your PR, which contains three modifications as I mentioned. Please reconfirm.

**Pull request merged**
